### ISSUE TITLE
NavBar and Request page Alignment.

### ISSUE THREAD

**Issue by nyambati** [andela/travel_tool_front#38]
Based on the designs the current request page deployment seems to be off, the Navigation is supposed to 1440px wide and centered. Adding `margin: 0 auto` to the class below should solve this issue.
https://github.com/andela/travel_tool_front/blob/af2518184646dc234330120bfc15b12df913fdf5/src/components/nav-bar/NavBar.scss#L1

The same also can be noticed on the request page. The main section should be `1440px` wide and centered `margin: 0 auto`, applying the said rules to the class below should bring the page to the desired state.
https://github.com/andela/travel_tool_front/blob/d9d452faafa7f7b68c00f66242d95b5254ab8ace/src/views/RequestsPage/_index.scss#L14

These changes should produce a request page as shown below 
<img width="1667" alt="screen shot 2018-08-13 at 02 13 11" src="https://user-images.githubusercontent.com/12892110/44007470-90c5d142-9e9e-11e8-96c0-c06f1b0e0b3c.png">

compared to the current state
<img width="1675" alt="screen shot 2018-08-13 at 02 11 11" src="https://user-images.githubusercontent.com/12892110/44007467-80352940-9e9e-11e8-9168-01cdb42de6b4.png">

**Comment by samuelkubai** [comment]
@nyambati the design actually doesn't leave any spaces on the ends it requires the page to grow full width (atleast the navbar on the extra large screens) and the navbar always to the far left. This issue is being worked on during this sprint and will attach the pull request that fixes it to this issue.


Thank you for raising the concern. Much appreciated.
